<?php

namespace AppBundle\Repository;

/**
 * EysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EysRepository extends \Doctrine\ORM\EntityRepository
{
}
